name: snakemake 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.0.0
  - python-dotenv
  - requests
  - scikit-learn
  - rouge
  - matplotlib 
  - pandas
  - markdownify
  - bs4
  - pip
  - pip:
    - deepeval
